platform :ios, '11.0'
use_frameworks!

# workaround to avoid Xcode 10 caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  # Automatic Capacitor Pod dependencies, do not delete
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCommunityTextToSpeech', :path => '../../node_modules/@capacitor-community/text-to-speech'
  pod 'CordovaPlugins', :path => '../capacitor-cordova-ios-plugins'
  pod 'CordovaPluginsResources', :path => '../capacitor-cordova-ios-plugins'
  # Do not delete
end

target 'App' do
  capacitor_pods
  # Add your Pods here
  pod 'Firebase/Messaging'
end

target 'Mobicoop' do
  capacitor_pods
  # Add your Pods here
  pod 'Firebase/Messaging'
end

target 'OuestGo' do
  capacitor_pods
  # Add your Pods here
  pod 'Firebase/Messaging'
end

target 'Movici' do
  capacitor_pods
  # Add your Pods here
  pod 'Firebase/Messaging'
end

target 'Picholines' do
  capacitor_pods
  # Add your Pods here
  pod 'Firebase/Messaging'
end

target 'PassPass' do
  capacitor_pods
  # Add your Pods here
  pod 'Firebase/Messaging'
end

target 'Grand Lyon' do
  capacitor_pods
  # Add your Pods here
  pod 'Firebase/Messaging'
end

target 'Txik Txak' do
  capacitor_pods
  # Add your Pods here
  pod 'Firebase/Messaging'
end

target 'MobiSDIS' do
  capacitor_pods
  # Add your Pods here
  pod 'Firebase/Messaging'
end
